[package]
name = "pagurus"
version = "0.2.0"
edition = "2021"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Ultra-portable game engine suited for offline 2D games powered by WebAssembly"
homepage = "https://github.com/sile/pagurus"
repository = "https://github.com/sile/pagurus"
readme = "README.md"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[workspace]
members = [
    "pagurus_game_std",
    "pagurus_wasmer",
    "pagurus_sdl_system",
    "pagurus_tui_system",
    "pagurus_android_system",
    "examples/android_snake",
    "examples/sdl_snake",
    "examples/sdl_runtime",
    "examples/tui_runtime",
    "examples/snake_game",
]