[package]
name = "pagurus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "pagurus_game_std",
    "pagurus_runtime_std",
    "pagurus_sdl_runtime",
    "pagurus_android_runtime",
]