[package]
name = "pagurus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[workspace]
members = [
    "pagurus_game_std",
    "pagurus_wasmer",
    "pagurus_sdl_system",
    "pagurus_android_runtime",
    "examples/snake", # TODO: examples/games/snake or examples/snake_game
]