[package]
name = "pagurus_wasmer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pagurus = { path = "../", version = "0.1" }
serde = "1"
serde_json = "1"
wasmer = "2"
