[package]
name = "snake_game"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.17"
orfail = "0.1"
pagurus = { path = "../../", version = "0.4" }
pagurus_game_std = { path = "../../pagurus_game_std/", version = "0.4" }
rand = "0.8"
